[package]
name = "hartree_fock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blas = "0.20"
openblas-src = "0.9"
lapack = "0.19.0"
